### ISSUE TITLE
Abstract types not implemented for code generators

### ISSUE THREAD

**Issue by mseri** [mirage/ocaml-rpc#69]
`pythongen`:
```
File "lib/pythongen.ml", line 45, characters 2-2770:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
Abstract _
File "lib/pythongen.ml", line 124, characters 21-851:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
Abstract _
```

`rpc_genfake`:
```
File "lib/rpc_genfake.ml", line 9, characters 2-1846:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
Abstract _
File "lib/rpc_genfake.ml", line 57, characters 2-2105:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
Abstract _
```

`htmlgen`:
```
File "lib/htmlgen.ml", line 20, characters 2-499:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
Abstract _
```

Also `cmdlinergen` and `markdowngen` are using a stub at the moment: https://github.com/mirage/ocaml-rpc/pull/65/commits/60d47bc2438e2dae25cce1e6ec4f3ff192879344

**Comment by mseri** [comment]
@jonludlam what should be the right thing to do?

**Comment by jonludlam** [comment]
For the abstract types we don't know what Rpc.t structure to expect, so in many of those cases there's not much we can do.

**Comment by mseri** [comment]
That's what I suspected. Would it be fine if I add a `failwith` as in `cmdlinergen` to `pythongen` and `rpc_genfake`, and a simple `"<abstract>"` in the `htmlgen`?

**Comment by jonludlam** [comment]
At least one of the problems in the pythongen.ml file is in typechecking - there's a good chance we should just make that succeed rather than `failwith`. Similarly with cmdlinergen actually - what the code in the other clauses is doing is this:

```ocaml
| Struct {sname; fields} ->
      Term.app
        (Term.pure (fun x ->
             let x = Jsonrpc.of_string x in
             match x with
             | Rpc.Dict _ -> x
             | _ -> failwith "Type error"))
        (Cmdliner.Arg.(required & pos (incr ()) (some string) None & pinfo))
```

so what it's doing is parsing the command-line argument as json and then doing a very simple check that it looks vaguely like it should - in this case, as the argument type is a `Struct`, the Rpc.t should be a `Dict`. For abstract types, we should probably just parse as json and then leave the typechecking up to the Abstract's `of_rpc` function.
